server:
  port: ${PORT:0}
spring:
  application:
    name: payment-service
  zipkin:
    base-ul: http://localhost:9411/
  h2:
    console:
      enabled: true
logging:
  file:
    name: C:/logs/microservices.log