server:
  port: 9192
spring:
  application:
    name: order-service
  zipkin:
    base-ul: http://localhost:9411/
  h2:
    console:
      enabled: true
  cloud:
    config:
      uri: http://localhost:9196
logging:
  file:
    name: C:/logs/microservices.log





